apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7glp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7glp
    app.kubernetes.io/part-of: tkrw-pr714-0075-0051-app
  name: devfile-sample-7glp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7glp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7glp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0051-tenant/tkrw-pr714-0075-0051-app/devfile-sample-7glp@sha256:8f5fa281bdf115fa7265cec458a371ff17a4cc6f1d786816e03ada7c07b8f774
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
